framework:
    messenger:
        transports:
            # Uncomment the following line to enable a transport named "amqp"
            live: live+redis://localhost/{tags}?broadcast=true

        routing:
            # Route your messages to the transports
            'Symfony\Component\Live\Message\LiveViewUpdate': live
